### ISSUE TITLE
Active Script Loading

### ISSUE THREAD

**Issue by zcmoore** [Williamgood/TimeGame_FinalProject#3]
When parsing an active script, the second line should be read as a path to a passive script.
Instead, the fourth line of each node is being read. 

Specifically, when parsing ActiveLorem.txt, the paths detected by the script loader are: "Second_ID:choiceDescription" and ":end"

**Comment by zcmoore** [comment]
"Split" is not updating for each element in the foreach loop. The left output returns the first line for the first 3 iterations.

**Comment by zcmoore** [comment]
Potential cause:
Second and third elements do not have the delimiter present, and so left out is not updated.

**Comment by Williamgood** [comment]
Most likely. There's also a parse into array that splits every occurrence
into an array 1,2,3 array has 1 2 3.
